# Generated by Django 3.1.3 on 2020-11-10 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreM', models.CharField(max_length=100, verbose_name='Nombre')),
                ('autorM', models.CharField(max_length=100, verbose_name='Autor')),
                ('manga_sta', models.CharField(choices=[('ON', 'ON GOING'), ('OFF', 'CANCELED'), ('FIN', 'FINISHED'), ('HIA', 'ON HIATUS')], max_length=3, verbose_name='Manga Status')),
                ('descriptionM', models.TextField(blank=True, max_length=1000, verbose_name='Descripción')),
                ('generoM', models.CharField(max_length=250, verbose_name='Generos')),
                ('rateM', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5)], verbose_name='Rate')),
                ('imagenM', models.ImageField(upload_to='mediafiles')),
            ],
        ),
    ]
