# Generated by Django 3.1.3 on 2020-11-10 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0002_auto_20201110_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='imageM',
        ),
    ]
