# Generated by Django 3.1.3 on 2020-11-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0003_remove_manga_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='imageM',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
