# Generated by Django 3.1.3 on 2020-11-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0004_manga_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='imageM',
            field=models.ImageField(blank=True, default='berserk.jpg', null=True, upload_to=''),
        ),
    ]
