# Generated by Django 3.1.3 on 2020-11-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0006_auto_20201111_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='capitulos',
            field=models.IntegerField(null=True, verbose_name='Capitulos'),
        ),
        migrations.AddField(
            model_name='manga',
            name='volumen',
            field=models.IntegerField(null=True, verbose_name='Volumenes'),
        ),
    ]
