# Generated by Django 3.1.3 on 2020-11-20 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0007_auto_20201112_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='imageM',
        ),
    ]
