# Generated by Django 3.1.3 on 2020-12-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0008_remove_manga_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='portadaManga',
            field=models.ImageField(blank=True, height_field=100, upload_to='', verbose_name='Imagen de portada', width_field=80),
        ),
    ]
