# Generated by Django 3.1.3 on 2020-11-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personas',
        ),
    ]
